apiVersion: apps/v1
kind: Deployment
metadata:
  name: one-pod-per-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: one-pod-per-node
  template:
    metadata:
      labels:
        app: one-pod-per-node
    spec:
      nodeSelector:
        kubernetes.io/role: node
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: one-pod-per-node
      containers:
      - image: gcr.io/google-samples/hello-app:1.0
        name: hello-app
