apiVersion: v1
kind: Pod
metadata:
  name: sidecar
spec:
  imagePullSecrets:
    - name: regcred
  volumes:
  - name: shared-logs 
    emptyDir: {}
  containers:  
  - name: main-container
    image: nginx
    resources:
      limits:
        cpu: "10m"
        memory: "10Mi"
    volumeMounts:
    - name: shared-logs
      mountPath: /usr/share/nginx/html
  - name: sidecar-container
    image: busybox # splunk adapter to ship the logs
    resources:
      limits:
        cpu: "10m"
        memory: "10Mi"
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date) >> /var/log/index.html; sleep 10;done"]
    volumeMounts:
    - name: shared-logs
      mountPath: /var/log
