apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-proxy
data:
  nginx.conf: |
    worker_processes 4;
    events { worker_connections 1024; }
    http {
        server {
            listen 80;
            location / {
                #rewrite ^/(.*)$ https://yahoo.com/$1 redirect;
                proxy_pass https://yahoo.com;
            }
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: ambassador
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/nginx
          name: nginx-config
      volumes:
      - configMap:
          defaultMode: 420
          name: nginx-proxy
        name: nginx-config
