apiVersion: v1
kind: Pod
metadata:
  name: probe-liveness-exec
spec:
  containers:
  - name: probe-liveness-exec
    image: k8s.gcr.io/busybox
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy;echo sleeping10s; sleep 10; rm -rf /tmp/healthy; echo filermoved;sleep 60
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5
      successThreshold: 1
      failureThreshold: 1
